# CMake generated Testfile for 
# Source directory: /insilications/apps/lapack/CBLAS/testing
# Build directory: /insilications/apps/lapack/kk/CBLAS/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CBLAS-xscblat1 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xscblat1" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/stest1.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xscblat1 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;59;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xscblat2 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xscblat2" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/sin2" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/stest2.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xscblat2 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;60;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xscblat3 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xscblat3" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/sin3" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/stest3.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xscblat3 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;61;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xdcblat1 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xdcblat1" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/dtest1.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xdcblat1 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;73;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xdcblat2 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xdcblat2" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/din2" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/dtest2.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xdcblat2 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;74;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xdcblat3 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xdcblat3" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/din3" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/dtest3.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xdcblat3 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;75;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xccblat1 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xccblat1" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ctest1.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xccblat1 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;87;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xccblat2 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xccblat2" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/cin2" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ctest2.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xccblat2 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;88;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xccblat3 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xccblat3" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/cin3" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ctest3.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xccblat3 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;89;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xzcblat1 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xzcblat1" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ztest1.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xzcblat1 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;101;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xzcblat2 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xzcblat2" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/zin2" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ztest2.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xzcblat2 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;102;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
add_test(CBLAS-xzcblat3 "/usr/bin/cmake" "-DTEST=/insilications/apps/lapack/kk/bin/xzcblat3" "-DINPUT=/insilications/apps/lapack/CBLAS/testing/zin3" "-DOUTPUT=/insilications/apps/lapack/kk/CBLAS/testing/ztest3.out" "-DINTDIR=." "-P" "/insilications/apps/lapack/TESTING/runtest.cmake")
set_tests_properties(CBLAS-xzcblat3 PROPERTIES  _BACKTRACE_TRIPLES "/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;12;add_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;103;add_cblas_test;/insilications/apps/lapack/CBLAS/testing/CMakeLists.txt;0;")
